services:
  keycloak:
    build: ./bundles/sirix-rest-api/src/test/resources
    ports:
      - 8080:8080
      - 8433:8433
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_LOG_LEVEL=DEBUG
      - KC_IMPORT=/opt/keycloak/data/import/realm-export.json
    restart: always
    volumes:
      - ./bundles/sirix-rest-api/src/test/resources/realm-export.json:/opt/keycloak/data/import/realm-export.json 
    entrypoint: ["/opt/keycloak/scripts/wait-for-keycloak.sh"]
    command: >
      start-dev
      --import-realm
      --http-relative-path=/
      --hostname-strict=false
      --proxy=edge
    networks:
      - auth-network
    healthcheck:
      test: "curl -f http://localhost:8080/ || exit 1"
      timeout: 3s
      start_period: 10s
      retries: 20
  server:
    build: .
    image: sirixdb/sirix
    ports:
      - "9443:9443"
    restart: always
    volumes:
      - /opt/sirix/sirix-data:/opt/sirix/sirix-data
      - ./bundles/sirix-rest-api/src/main/resources/cert.pem:/opt/sirix/sirix-data/cert.pem
      - ./bundles/sirix-rest-api/src/main/resources/key.pem:/opt/sirix/sirix-data/key.pem
      - ./bundles/sirix-rest-api/src/main/resources/sirix-docker-conf.json:/opt/sirix/sirix-docker-conf.json
      - ./bundles/sirix-rest-api/src/test/resources/logback-test.xml:/opt/sirix/logback-test.xml
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - auth-network
    links:
      - keycloak
networks:
  auth-network:
    driver: bridge

